version: '3.8'
services:
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
            MYSQL_DATABASE: teamsphere_db
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
    rabbitmq:
        image: rabbitmq:management
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        command: >
            bash -c "rabbitmq-plugins enable rabbitmq_stomp && rabbitmq-server"
        ports:
            - "61613:61613"
            - "15672:15672"
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
    kafka:
        image: confluentinc/cp-kafka:7.4.0
        container_name: kafka
        hostname: kafka
        ports:
            - "9092:9092"   # client
            - "9093:9093"   # controller listener
        environment:
            CLUSTER_ID: "F3_Br_pIQROFaarWUPABDA"
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
            KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_LOG_DIRS: "/var/lib/kafka/data"
        command:
            - bash
            - -c
            - |
                echo "CLUSTER_ID is: $CLUSTER_ID"
                if [ ! -f /var/lib/kafka/data/meta.properties ]; then
                  echo "Formatting KRaft storage for cluster with ID: $CLUSTER_ID..."
                  kafka-storage format \
                    --cluster-id "$CLUSTER_ID" \
                    --config /etc/kafka/kraft/server.properties
                else
                  echo "Skipping this step..."
                fi
                exec /etc/confluent/docker/run
        volumes:
            - kafka-data:/var/lib/kafka/data
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        command: ["redis-server", "--appendonly", "yes"]

volumes:
    mysql-data:
    rabbitmq-data:
    kafka-data:
    redis-data:








