_logging_pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5level} log_level=\"%level\" ${PID:- } --- [thread=\"%thread\", httpMethod=\"%X{httpMethod:-null}\", httpRequestURI=\"%X{httpRequestURI:-null}\", X-Request-ID=\"%X{requestId:-null}\"] [%15.15t] %-40.40logger{39} : %replace(%msg){'\r\n|\n', '\u2028'} %replace(%ex{full}){'\r\n|\n', '\u2028'}%nopex"
_logging_pattern_console: "${_logging_pattern}%n"
logging:
  pattern:
    console: ${_logging_pattern_console}

jwt:
  publicKey: ${PUBLIC_KEY}
  privateKey: ${PRIVATE_KEY}
  audience: "localhost:3000"

cloudflare:
  api:
    accountID: ${CLOUDFLARE_ACCOUNTID}
    key: ${CLOUDFLARE_KEY}

server:
  port: 5454
  tomcat:
      connection-timeout: 30000

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_USER_PASSWORD}
        url: ${MYSQL_DATABASE_DEV_HOST}
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
    rabbitmq:
        host: ${RABBITMQ_HOST}
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}
        port: 30716
        requested-heartbeat: 580
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB
    data:
        redis:
            host: localhost # TODO: change to vault var before PR
            port: 6379 # TODO: change to vault var before PR
            timeout: 2000ms # TODO: change to vault var before PR
            jedis:
                pool:
                    max-active: 20 # TODO: change to vault var before PR
                    max-idle: 10 # TODO: change to vault var before PR
                    min-idle: 2 # TODO: change to vault var before PR

resilience4j:
    ratelimiter:
        instances:
            userService:
                limit-for-period: 10  # # of requests allowed per period
                limit-refresh-period: 60s  # Time period for rate limiting
                timeout-duration: 1s  # How long to wait for permission
                register-health-indicator: true
                event-consumer-buffer-size: 100

app:
  environment:
    ALLOWED_ORIGINS:
      - ${ALLOWED_ORIGIN}
    cache:
        message-ttl: 300
        chat-ttl: 600
        user-ttl: 1800

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  info:
    env:
      enabled: true
    build:
      enabled: true

info:
  app:
    version: ${APP_VERSION}
